default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>

development:
  <<: *default
  database: kapital_development

test:
  <<: *default
  database: kapital_test

production:
  <<: *default
  database: kapital_production
  username: kapital
  password: <%= ENV["KAPITAL_DATABASE_PASSWORD"] %>
